apiVersion: policies.kyverno.io/v1
kind: GeneratingPolicy
metadata:
  name: generate-ingress
spec:
  matchConstraints:
    resourceRules:
      - apiGroups: ['']
        apiVersions: ['v1']
        operations: ['CREATE']
        resources: ['services']
  variables:
    - name: host
      expression: object.metadata.name + "." + object.metadata.namespace + ".neworleans-la.xyz"
  generate:
    - expression: |
        generator.Apply(
          object.metadata.namespace,
          [{
            "kind": dyn("Ingress"),
            "apiVersion": dyn("networking.k8s.io/v1"),
            "metadata": dyn({
              "name": dyn(object.metadata.name),
              "namespace": dyn(object.metadata.namespace),
              "annotations": dyn({
                "do-not-add-cert-manager.io/cluster-issuer": "letsencrypt-production"
              })
            }),
            "spec": dyn({
              "tls": [{
                "hosts": dyn([ variables.host ]),
                "secretName": dyn(object.metadata.name)
              }],
              "rules": [{
                "host": dyn(variables.host),
                "http": dyn({
                  "paths": [{
                    "path": dyn("/"),
                    "pathType": dyn("Prefix"),
                    "backend": dyn({
                      "service": {
                        "name": dyn(object.metadata.name),
                        "port": dyn({
                          "number": 80
                        })
                      }
                    })
                  }]
                })
             }]
          })
        }])

