---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: database-password
  namespace: ex-ss-stg
spec:
  encryptedData:
    password: AgBdVgvB6tNJJqNWJoFRC5cOa7x19UDmUblyCkpi1K9hDdjvGgNQbp0WTjuCAFSBryxehSBHQY0eIeBrCFsEicHt/Lwkt8RNSWCm4m0Rn2aOHExWiqRLO4td0Owugj7/fFdbZoFPWtZULM4HIwSE/k7NwXzuAiI2TfwGsfOu7A1jZNDtqqDpJjIwTTJOqpCAXqATEpOGNybnSid3xeT8eOMFs3KP8eecaKPNtXP8jHiH7UFaZgLd0EJkXFxscpkxSCUN7KrqX+BC2WKFEaRU4DJl4bmQEn8O0IMpjcoaUd8bdic+nTQzfHuetZsQSeASA6fyTczUJcFIpMSocKyOubR8PiKAAghkEIYkEvoHu0ey6db/Ikdo5MtypRcIzX/uh9OSu+Hvto+JwRK+MhnJcoiq3RmrglKPqiNvJXY2V9EvlkyiV6ZqTJiZ/Bp4euyuTCincMTp6GO7LUoJIs5NFm3CufHOrFpJnsiMqopiM/jmiAy+A5saOJ4TsK7BRA3vGgTogRzGvYOGy0LMHM/sKNtapO5kyrD379B9quKqJ0mKnQo6uKNddOUVZG22Cx1gJeCftppPn17m8d3AehkJXV9AiuuuAthC2NoOY+TwQDzJkHEIrSAaveZJF+f+Mz2JAcBwG5OiEenFEYCUfelQWZyz0GuFFuGxnm93NYieve7QzWB8gmpNgH5tf4fq/oywougB7DW6J2PWls2pKyNVSQ3TAbXabluHfg==
  template:
    metadata:
      creationTimestamp: null
      name: database-password
      namespace: ex-ss-stg
