---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: logging-api-token
  namespace: ex-ss-stg
spec:
  encryptedData:
    token: AgBtN/wj3byVJGULXJHyQeTn+6dKDVWTC/wr3zrYVGCxPPlejxAr3DeSnamCbWY6KqjsixllqfkTdygWFvyz4mZAn8Tpgf8cqWnN4bU3MvMVpPX7GBQJZZAAl0OifKyfafJtS6d+hzStNZBe+q0Wq9TB/5CTIxW3KrKP0NxVHOFrQlzFBbpcjikoLS/xFw5rvr156zMVL2DwVzKz9GG96ioWeZhqol+zTqhN+1yT+oy+d4f0RULGXibzasp5aTHu5n98+u70SZ3lHN23Ux76LOt3F9qxXhMJz9LTT9MFNuhdsaRa4aDGrjRQbaFcXrJeXUjSGp4mZS1PXNBfdsWxRaPdZ1ObCPph7C4kb50FE3U6lxDxk8FXakJhPhhOaXDhdgLkLW+70EUVPlHyl52rZnPnjDGqNhHpjj70OPYVct4ASbKSUn8iZqHlSVsJtFJYXo9j/HxuKgEtlz6ndSX4AOHbYGEDQiJoTE5CFd++zNYslnS79uoDTrpiYLJ3kY5Aaa3VcaduZCGNZW7jxHqjnfnnOdspEyD0/g5QfZZZIubcXB9bDRnN547jsHPBkXTR07z6JHT6BuD2csfSUAr7rIFIK7WQ8le0tBFB2tMNtPFOvudrcc7IgHNqMAkl8fkfUzH34b5eRL69N9Spoyspx5UaGjY74ajtZo19tY4oJjQGA8L8ss9l0LESJFCRLMOOOtg7DXsr/0hM4yfN9hw=
  template:
    metadata:
      creationTimestamp: null
      name: logging-api-token
      namespace: ex-ss-stg
