---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: logging-api-token
  namespace: ex-ss-dev
spec:
  encryptedData:
    token: AgAswMMdj9GFv9tTiWeXBV56N5PPSd6LpW6xV63UfjXh8ovmR7SRsr/EgDJs/qPXIEbnqpvZF7L3qDCsOm2gtL5b1qgrehaOTZ9SAZu7T7emC8Hmwnmbi/YLsRlJSeY9AZ8K4ZuCBWjAf/ome4ct5LfIx/qXVccn+PggN56BHaYr4n/7l/EtQ3s8ic7uEdE9Y60s2nCbJKVu2mBY8GTnIZIF+jin6Hpkh6W+UrAqFsqkXsWQtti05ONPF/9LHam53EXfluVSH19ZdqTU6I7R0l0h/mA753bihdks4y/Jj2POgGELwWzFyxaDCZQIOPFnTMwXfMkssALDVYQAc94QmpA/xyVXQckULI8rqIPVJIj7qFqDnTFLvW5jOrP+qnUI0pETbuPZAkBAt89ICccBn19iz5RfPlWA2I2UYfCxHxk1jY4TD4Blub7PFJFdkMzMAJMTW/HI2SFaawTBEoFx5B83mCV6uD/PfdCBpuvGJvwf6aA8/BkJ4qCrUTvTGE9sjSph3XFLQc4KOZeI0H4u1ZKnsrUCS8MHydAtQB9FUMhylcDURqzsO9EHQOpKEGC7RX04x1//8Y8TNjjCm5Z5H5Fzlko8TLH//SRheEuqLBuEe47Gg87/2lfNhFPRbTu+B8lsTVyRFDwtgTf/WUsWbWMj7H+MZmCT05xEJd0b2uK1Nh1XxqUu38wCfqG1C78UA1Ic74ecJCW8HPOHGKw=
  template:
    metadata:
      creationTimestamp: null
      name: logging-api-token
      namespace: ex-ss-dev
