---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: database-password
  namespace: ex-ss-dev
spec:
  encryptedData:
    password: AgAvCaGUtUfZWvR+B9cwkQi9Z4gEy63Z/ECFwzwWjb/L2z6qUN28SeqDXZg+bDykYI+JKEapwPYCKhN0SktlAwwUcbBJoN8WtVBcvlqqe/6uzb/zhbLzA2nDwvOHNlkhvxVRcjXKBzXKnBEx0/NfvO3z3f3XDWWtbPNFO1Sg6/S5ak6tqMiT4EEQctLBH1vaSTXTEOlfZg6nDcWnThXvA3rygnKIUZPeTbTAbKpiW/RdY5THYN7ukaYsQrfG/WnaTebUJ2FQuQ2O5uNBXO6UGGh51bzxQQU4i52+tLAUVYImERR1cKuNztD1BSNggy+XU6vPVyywNfBhJADMknXf2LDkJPlN9znt7pf7RHNGQUP+HBi3+CDWky18nP4eyJFIUGIU+w4k8VYO5Tyj92lBGgOUrcOdTC0th866XQhMCSWG5s6NuTx30xsxyZjYXJ/vMXCxAFSDicrr0lAjKscYvYfs7bnGtMftzSKIWId0jBdXuGYDuiDzTZoKQtjPH5l5eVGNqgnRtiAD/Bf1yc4eAdkl9W9TcnpmhAjnnIzALlYJnniL1FEHEOyITHFKxfX++kn88ZlRQ9/q4awLcFl7ky/PrjFWA7jIWh3x/kpYUOMzTV16BwyDS/9+IIt0p8jjDsQfDyvgbbbu2hOSrg6neBPOTQS+EIEOtAiWMCKwlQ5GHJlzFsAihDNyz/vwFstcAs19YhXnPX3g/rUsgTLvucqCdcO1pLk8BA==
  template:
    metadata:
      creationTimestamp: null
      name: database-password
      namespace: ex-ss-dev
