apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blue
  namespace: argocd
spec:
  destination:
    namespace: argo-blue
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/blue/manifests
    repoURL: https://github.com/jpetazzo/2026-05-hi5
    targetRevision: main
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
