apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helmcoins-rng
  namespace: argocd
spec:
  destination:
    namespace: argo-helmcoins
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      releaseName: rng
      valuesObject:
        readinessProbe:
          httpGet:
            path: /1
            port: 80
    path: charts/generic
    repoURL: https://github.com/jpetazzo/2026-05-hi5
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
